apiVersion: v1
kind: Secret
metadata:
    name: syslog-secret
    namespace: {{ .Release.namespace }}
type: Opaque
stringData:
    SYSLOG_PASSKEY: {{ .Values.samurai.passkey | default "" }}
    SYSLOG_APIKEY: {{ .Values.samurai.apikey | default "" }}

