apiVersion: apps/v1
kind: Deployment
metadata:
  name: syslog-{{ .Release.Name }}
  namespace: {{ .Release.namespace }}
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: samurai-falco-syslog
  template:
    metadata:
      labels:
        app: samurai-falco-syslog
    spec:
      containers:
        - name: syslog
          image: {{ .Values.samurai.image | default "nttsecurityes/cts_syslog:2024.11.19-187"}}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: syslog-config
            - secretRef:
                name: syslog-secret
          volumeMounts:
            - name: syslog-state
              mountPath: /var/cache/syslog/
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - ps -ef | grep rsyslogd | grep -v grep
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - ps -ef | grep rsyslogd | grep -v grep
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
      - name: syslog-state
        emptyDir:
          sizeLimit: 500Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
