apiVersion: v2
name: falco-for-samurai-mdr
description: Falco with a Samurai MDR collector
version: 1.3.0
appVersion: "0.41.3"
keywords:
 - monitoring
 - security
 - alerting
home: https://security.ntt/
dependencies:
 - name: falco
   version: 6.2.5
   repository: https://falcosecurity.github.io/charts/
