apiVersion: v2
name: falco-for-samurai-mdr
description: Falco with a Samurai MDR collector
version: 1.4.0
appVersion: "0.43.0"
keywords:
 - monitoring
 - security
 - alerting
home: https://security.ntt/
dependencies:
 - name: falco
   version: 8.0.1
   repository: https://falcosecurity.github.io/charts/
