apiVersion: v2
name: falco-for-samurai-mdr
description: Falco with a Samurai MDR collector
version: 1.5.0
appVersion: "0.45.0"
keywords:
 - monitoring
 - security
 - alerting
home: https://security.ntt/
dependencies:
 - name: falco
   version: 9.2.0
   repository: https://falcosecurity.github.io/charts/
